### ISSUE TITLE
pypi release?

### ISSUE THREAD

**Issue by sappelhoff** [wmvanvliet/mne-faster#2]
Hi @wmvanvliet I want to use the epoch rejection step from the FASTER pipeline in one of my projects. Would you be willing to get this package up on PyPI?

**Comment by wmvanvliet** [comment]
sure

**Comment by wmvanvliet** [comment]
done! https://pypi.org/project/mne-faster/

**Comment by sappelhoff** [comment]
Thanks! :rocket:
