### ISSUE TITLE
MAINT: Release?

### ISSUE THREAD

**Issue by larsoner** [wmvanvliet/mne-faster#3]
@wmvanvliet we are making standalone installers for MNE-Python with things like MNE-Connectivity, MNE-BIDS, MNE-FASTER etc. bundled. Do you know if the current MNE-FASTER release is fully compatible with MNE-Python? If so, then we can include it.

If not, can you quickly fix any bugs and cut a new release? If you can't do it in the next few days (our current MNE-Python release goal), then we can omit MNE-FASTER from the first set of installers, and update the installers later (in weeks or months, etc.) when MNE-FASTER becomes compatible with 1.0. (We can update the installers separately -- it doesn't have to be done at release time.)

**Comment by wmvanvliet** [comment]
I'll check as soon as I have some time.

**Comment by wmvanvliet** [comment]
Are you going to bundle [mne-rsa](https://github.com/wmvanvliet/mne-rsa) as well?

**Comment by larsoner** [comment]
Not sure, @hoechenberger do you bundle mne-rsa?

**Comment by hoechenberger** [comment]
I didn't even know about this package before 😅 but sure, why not! Any additional suggestions? :)

**Comment by wmvanvliet** [comment]
If you want the complete set, there's also [mne-microstates](https://github.com/wmvanvliet/mne_microstates)

**Comment by wmvanvliet** [comment]
Ok, MNE-faster is now fully 1.0 compatible.

**Comment by hoechenberger** [comment]
> Ok, MNE-faster is now fully 1.0 compatible.

Amazing! Could you please cut a new release? At least add a new tag here on GH? (Optimally, also publish to PyPI)
Thank you!

**Comment by wmvanvliet** [comment]
done!

**Comment by hoechenberger** [comment]
@wmvanvliet I saw you just published a release to PyPI, great!

But there seems to be something off with the sdist (`mne-faster-1.1.win-amd64.zip`), it contains the following path structure:

```shell
❯ unzip mne-faster-1.1.win-amd64.zip
Archive:  mne-faster-1.1.win-amd64.zip
   creating: Users/
   creating: Users/wmvan/
   creating: Users/wmvan/miniconda3/
   creating: Users/wmvan/miniconda3/Lib/
   creating: Users/wmvan/miniconda3/Lib/site-packages/
   creating: Users/wmvan/miniconda3/Lib/site-packages/mne_faster/
   creating: Users/wmvan/miniconda3/Lib/site-packages/mne_faster-1.1-py3.9.egg-info/
   creating: Users/wmvan/miniconda3/Lib/site-packages/mne_faster/__pycache__/
  inflating: Users/wmvan/miniconda3/Lib/site-packages/mne_faster/faster.py
  inflating: Users/wmvan/miniconda3/Lib/site-packages/mne_faster/__init__.py
  inflating: Users/wmvan/miniconda3/Lib/site-packages/mne_faster/__pycache__/faster.cpython-39.pyc
  inflating: Users/wmvan/miniconda3/Lib/site-packages/mne_faster/__pycache__/__init__.cpython-39.pyc
  inflating: Users/wmvan/miniconda3/Lib/site-packages/mne_faster-1.1-py3.9.egg-info/dependency_links.txt
  inflating: Users/wmvan/miniconda3/Lib/site-packages/mne_faster-1.1-py3.9.egg-info/PKG-INFO
  inflating: Users/wmvan/miniconda3/Lib/site-packages/mne_faster-1.1-py3.9.egg-info/requires.txt
  inflating: Users/wmvan/miniconda3/Lib/site-packages/mne_faster-1.1-py3.9.egg-info/SOURCES.txt
  inflating: Users/wmvan/miniconda3/Lib/site-packages/mne_faster-1.1-py3.9.egg-info/top_level.txt
```

I don't think this is right? Or is this how sdists are built on Windows? I haven't tried installing it yet. I guess I'm also surprised this is somehow tied to a platform.

**Comment by wmvanvliet** [comment]
hrm, that's weird. This is just build with `python setup.py bdist`

**Comment by wmvanvliet** [comment]
removed the `.zip` file and replaced with `.tar.gz` that should be better

**Comment by hoechenberger** [comment]
> hrm, that's weird. This is just build with `python setup.py bdist`

Interesting! I think you should explicitly build an `sdist`, too. This should then be the "right" thing for all platforms (and is what we need for conda-forge)

**Comment by larsoner** [comment]
"bdist_wheel sdist" is even better I think
