### ISSUE TITLE
Get EEG data

### ISSUE THREAD

**Issue by Shahin-rmz** [wmvanvliet/mne-faster#4]
Hello, 
Thanks for the release, I will check MNE faster and see what's the difference between 
My question is not directly relevant to MNE (and MNE fater), but rather EEG itself.
Is there any product in which we can get EEG at home?
I mean something commercially affordable which can be used by the patients at home to send the data to their doctors or record it for later use.
[This](https://www.neurotecheeg.com/neurologists/) is **not** what I want.

**Comment by wmvanvliet** [comment]
Nothing medically approved I'm afraid. In terms of cheapish EEG headsets you got things like the gTec nautilus and Emotiv Epoc

**Comment by Shahin-rmz** [comment]
Thanks so much @wmvanvliet .
As Always very helpful.
